version: '3.8'

services:
  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus:latest'
    restart: 'unless-stopped'
    user: 'root'
    hostname: 'prometheus'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './config/:/etc/prometheus/:ro'
      - 'prometheus:/prometheus/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.internal.local`)'
      - 'traefik.http.routers.prometheus.entrypoints=web'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
    networks:
      - web
networks:
  web:
    external: true
volumes:
  prometheus:
    #external: true
