{
 "title": "Home Dashboard",
 "description": "Home network monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Speed test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Download Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Ping Latency Timeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ping Latency (ms)" }
   ],
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping Latency" }
   ]
  },
  {
   "title": "Speedtest Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbits", "label": "Speed Mbps" }
   ],
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" },
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_unique_domains" }
   ]
  },
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_reply", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" },
    {}
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_forward_destinations", "legendFormat": "{{ destination }}" }
   ]
  },
  {
   "title": "Unique clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  }
 ]
}