version: '3.8'

services:
  watchtower:
    container_name: 'watchtower'
    image: 'containrrr/watchtower:latest'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_MONITOR_ONLY: 'false'
      WATCHTOWER_SCHEDULE: '0 0 2 * * *'
    networks:
      - web

networks:
  web:
    external: true
